export const SET_ACCOUNTS = 'SET_ACCOUNTS'
export const POST_ACCOUNT = 'POST_ACCOUNT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const PUT_ACCOUNT = 'PUT_ACCOUNT'
export const SET_LOADING = 'SET_LOADING'
export const SET_TOTAL = 'SET_TOTAL'
export const SET_IS_LOGIN = 'SET_IS_LOGIN'
